### ISSUE TITLE
dump(): TypeError: Cannot use 'in' operator to search for '_id'

### ISSUE THREAD

**Issue by Artanis** [nolanlawson/pouchdb-replication-stream#28] opened 2015-03-21 07:42 UTC
I'm trying to use this in the browser, having found `createWriteStream()` attached to PouchDB instances (I assume instructions in Readme are for node, as they place it at `fs.createWriteStream()`).

When I call dump, I get `TypeError: Cannot use 'in' operator to search for '_id' in {"version":"1.1.1","db_type":"idb","start_time":"2015-03-21T07:25:34.570Z", ...}` at [pouchdb.replication-stream.js:10883](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10883)

A little poking through the code revealed that that line is using the in operator on a string, and that several functions up the stack, `JSON.stringify()` had been used.

I have replicated this in the following code, though I may be doing something wrong:

    <!DOCTYPE html>
    <html>
      <head>
        
        <script src="pouchdb.js"></script>
        <script src="pouchdb.replication-stream.js"></script>
      </head>
      <body>
        <script>
          var bug = function () {
            var db = new PouchDB('test');

            db.put({
              "_id": "testing/broken-write",
              "type": "testing",
              "name": "broken-write"
            });

            var ws = db.createWriteStream();

            db.dump(ws, { batch_size: 1})
              .then(function (res) {
                console.log(ws);
                console.log(res);
            });
          };

          bug();
        </script>
      </body>
    </html>

**Comment by nolanlawson** [comment] 2015-03-21 15:06
Can you point to the line in the source code that causes this?

**Comment by Artanis** [comment] 2015-03-22 21:56
Sorry, should have done that to begin with. Everything I'm doing is in the browser, though, so that's all I can inspect.

The `JSON.stringify()` call I found is at [pouchdb.replication-stream.js:50](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L50), in a `.then()` callback function. It looks like [index.js:49](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/index.js#L49).

Chrome stack trace:
[WriteStream._write (pouchdb.replication-stream.js:10883)](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10883)
[doWrite (pouchdb.replication-stream.js:10291)](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10291)
[writeOrBuffer (pouchdb.replication-stream.js:10281)](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10281)
[Writable.write (pouchdb.replication-stream.js:10248)](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10248)
**[(anonymous function) (pouchdb.replication-stream.js:50)](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L50)**

There's another at [pouchdb.replication-stream.js:7415](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L7415), which causes a similar error when attempting to write out the actual documents (I removed the stringify call at line 50 to get to this). As far as I can tell, this line does not appear elsewhere in the repository, and may be from a dependency.

Removing both stringify calls removes the error ... but I haven't figured out how to get at the data that's been written to the stream yet (the code I posted in the issue body is almost exactly what I wrote to start learning how to use pouchdb-replication-stream), so I can't tell you if this 'solves' the problem, or just replaces it with a different, silent error.

**Comment by nolanlawson** [comment] 2015-03-23 16:41
That's really weird. What's the `header` object when it occurs? Can you provide a reproducible test case? (Sorry, but I'm really busy at the moment, so I don't have time to debug this.)

**Comment by nolanlawson** [comment] 2015-03-23 16:43
Also yeah, it's very likely that this is a bug in how browserify is browserifying Node `stream`s for the browser. If you cannot reproduce the bug in Node, then you may want to look at [stream-browserify](https://github.com/substack/stream-browserify).

**Comment by calvinmetcalf** [comment] 2015-03-24 00:25
_write is often the base of an error because that is often the top of the stack, this case we are writing a string [here](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L50)  but then [here](https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10883) we are assuming it has an '_id' property. Guess what happens in node if you look for a string inside another string

```
'bar' in 'baz'
TypeError: Cannot use 'in' operator to search for 'bar' in baz
    at repl:1:7
    at REPLServer.defaultEval (repl.js:124:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:277:12)
    at emitOne (events.js:77:13)
    at REPLServer.emit (events.js:166:7)
    at REPLServer.Interface._onLine (readline.js:195:10)
    at REPLServer.Interface._line (readline.js:534:8)
    at REPLServer.Interface._ttyWrite (readline.js:811:14)
```

it doesn't print the quotes around the string you looked in, meaning I probably need a check for a string [here](https://github.com/calvinmetcalf/PouchStream/blob/7775885f19e704ae3061d10ed2214ccd95dce4d1/writable.js#L24)

**Comment by Artanis** [comment] 2015-03-25 01:32
@nolanlawson, the header object is `{"version":"1.1.1","db_type":"idb","start_time":"2015-03-24T23:55:40.925Z","db_info":{"doc_count":18468,"update_seq":18468,"idb_attachment_format":"base64","db_name":"test","auto_compaction":false}}`, just before it becomes a string for writing. As earlier, it is still a string when it hits PouchStream and has the `in` operator used on it.

Regarding stream-browserify, the code in that project is nearly identical to the node stream module. It seems unlikely that browserify is inserting `JSON.stringify()` calls, but I am not familiar with the inner-workings. I managed to I track down the second instance I noted in [ldjson-stream/index.js:27](https://github.com/maxogden/ndjson/blob/master/index.js#L27).

@calvinmetcalf, The usage example for PouchStream suggests that objects should be written, rather than strings. Are strings valid arguments for `write()` and this is instead a bug in PouchStream?

As for the error message, I'm seeing that same lack-of-quoting behavior in Chrome DevTools, too. It's confusing until you realize what is happening. A quick search pulls up [a stackoverflow question](http://stackoverflow.com/questions/23673184/uncaught-typeerror-cannot-use-in-operator-to-search-for-in-json-string), and a [post to the Backbonejs Google Group](https://groups.google.com/forum/#!topic/backbonejs/n-Jpz5jSi4c), though neither of those touched on the elephant in the room: errors should be printing unambiguous values. Any idea where something like this gets reported?

**Comment by calvinmetcalf** [comment] 2015-03-30 17:46
should be fixed by version 0.4.1 of pouch-stream

**Comment by nolanlawson** [comment] 2015-04-06 14:56
@Artanis please reopen if still not fixed

**Closed by nolanlawson** 2015-04-06 14:56 UTC

**Comment by Artanis** [comment] 2015-04-17 22:05
Sorry for the delay. Was unexpectedly busy, myself.

This looks to be fixed.
