### ISSUE TITLE
Possible in browser?

### ISSUE THREAD

**Issue by Canifex** [nolanlawson/pouchdb-replication-stream#29] opened 2015-04-19 19:59 UTC
Is there any option to open a replication stream in a browser? My intention is to write a web rtc adapter for it, but only if I could replicate in browser. 

All examples in the readme reference to nodejs. How can I open a webrtc-stream in the browser, or write an adapter to do this? It seems that all stream adapters are based on nodejs..

**Comment by calvinmetcalf** [comment] 2015-04-20 14:05
use browserify and you can use something like [this](https://www.npmjs.com/package/simple-peer) with it

**Comment by nolanlawson** [comment] 2015-04-20 19:56
Or just directly download the browserified file: https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js

**Comment by sonnylazuardi** [comment] 2015-04-20 23:54
How to use it on browser? like this? It is still not working

         var replicationStream = new WritableStreamPouch();
         PouchDB.plugin(replicationStream.plugin);
         PouchDB.adapter('writableStream', replicationStream.adapters.writableStream);

**Comment by nolanlawson** [comment] 2015-04-21 02:07
Hm, can you provide a test case and what browser you're using? I test this thing in Travis; here it is running in PhantomJS and Firefox: https://travis-ci.org/nolanlawson/pouchdb-replication-stream

**Comment by nolanlawson** [comment] 2015-04-21 02:08
Wait, your `test` variable is not defined...

**Comment by sonnylazuardi** [comment] 2015-04-21 02:21
The first line is the variable test. I am using chrome 42.0. I didnt use browserify. how to load the pouchdb replication stream? WritableStreamPouch is not defined? what should be assigned to replicationStream?

      var test;
      var replicationStream = new WritableStreamPouch();
      PouchDB.plugin(replicationStream.plugin);
      PouchDB.adapter('writableStream', WritableStreamPouch);
      var db = new PouchDB(_ArrangementDB);
      db.dump(test).then(function(result) {
        console.log(result);
      });

**Comment by nolanlawson** [comment] 2015-04-21 02:36
Yep, streams have not been finalized by the W3C yet (http://www.w3.org/TR/streams-api/), but you can use browserified Node streams in the Browser. E.g. try browserifying the MemoryStream example from the README.

**Comment by nolanlawson** [comment] 2015-04-21 02:38
Or if you're unfamiliar with browserify, you can also just download MemoryStream from wzrd.in: https://wzrd.in/standalone/memorystream@latest

**Comment by Canifex** [comment] 2015-04-22 15:21
Thanks for the great support! Never heard of browserify before, thanks for that hint!

I tried to establish a webrtc stream using the browserified replication-stream (https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js) and the simple-peer.min.js from https://www.npmjs.com/package/simple-peer with this coffee-code:

```coffee
(($) ->
  $ ->
    peer1 = new window.SimplePeer initiator: true
    peer2 = new window.SimplePeer

    peer1.on 'signal', (data) ->
      # when peer1 has signaling data, give it to peer2
      peer2.signal data

    peer2.on 'signal', (data) ->
      # same as above, but in reverse
      peer1.signal data

    peer2.on 'data', (data) ->
      # got a data channel message
      console.log 'got a message from peer1: ' + data

    from_db = new PouchDB('db')
    to_db = new PouchDB('db_cpy')

    from_db.dump(peer1).then (res) ->
      console.log res
      console.log "should be 'ok'"

    to_db.load(peer2).then (res) ->
      console.log res
      console.log "should be 'ok'"
) jQuery
```

Dumping works awesome, console shows me exactly what to expect following the "design" chapter in the readme of pouchdb-replication-stream, but only if I leave out the load-command. If I execute the code exactly as stated above, I still get a {ok: true} from the dump function, but console only shows the header of replication-stream:
```
"got a message from peer1: {"version":"1.2.1","db_type":"idb","start_time":"2015-04-22T15:11:29.920Z","db_info":{"doc_count":2,"update_seq":8,"idb_attachment_format":"binary","db_name":"db","auto_compaction":false}}
"
```

But does not seem to transfer all the docs or the {seq: x} messages I have seen before. Instead, an error occures (which might be the reason why there are no further console entries):
> TypeError: Invalid non-string/buffer chunk
The error is thrown in this line: https://github.com/nolanlawson/pouchdb-replication-stream/blob/master/dist/pouchdb.replication-stream.js#L10282

In the error case, the variable "chunk" contains an Uint8Array  containing over 200 integers.


Anyone of you may help me again? I'm pretty new to Pouch & Node-streams. :/

**Comment by nolanlawson** [comment] 2015-04-22 15:48
I'm very new to streams as well, and the browserified streams are a pretty new thing AFAIK.

Can you provide a live test case? Also most likely the bug is in the browserified version of streams or MemoryStream (not this module), unless you can reproduce the same bug in Node.js.

**Comment by calvinmetcalf** [comment] 2015-04-22 17:26
The issue is that you passing an array buffer to something that expects a
browserify buffer

**Comment by calvinmetcalf** [comment] 2015-04-22 17:52
you can do 2 things, either put in another stream to do the conversion for you something like

```coffee
through = require('through).obj
toBuffer = through((chunk, _, next) ->
  this.push new Buffer(chunk)
  next()
)
to_db.load(peer2.pipe(toBuffer))
```

we can also fix this here

**Comment by calvinmetcalf** [comment] 2015-04-22 17:59
(fyi it's a bug in streams that it doesn't recognize the buffer as a buffer which should be fixed in the next version of readable streams)

**Comment by nolanlawson** [comment] 2015-04-22 18:48
Fixed in 1.2.2.

**Comment by Canifex** [comment] 2015-04-23 12:17
Thanks for your fast answers! I updated my pouchdb-replication-stream.js to the lastest version - now console shows me the whole stream logged in dump(), not just the header, but also all entries. This differs from the behaviour before the update, see above. But the load()-process still is not working, with the same error message.

I uploaded a live example here: http://bit.ly/1GlRxhQ

Thanks for your help!!

**Comment by calvinmetcalf** [comment] 2015-04-23 13:08
found the problem, really old version of browserify being used to build the
bundle

**Comment by nolanlawson** [comment] 2015-04-23 13:08
I'm really not an expert on streams, but @calvinmetcalf said in IRC

> the module if people want to use streams without browserify is probably https://wzrd.in/standalone/readable-stream@latest not memory stream

BTW hit us up in the #pouchdb room in Freenode IRC if you get stuck. Hopefully once we get this figured out, we can add an example to the README, because I imagine many people will get stuck on this. :)

**Comment by nolanlawson** [comment] 2015-04-23 13:08
@calvinmetcalf ah okay, I can fix that. been slowly fixing it for all my plugins

**Comment by nolanlawson** [comment] 2015-04-23 13:26
OK, give v1.2.3 a shot.

**Comment by nolanlawson** [comment] 2015-04-23 13:30
Also @Canifex protip: if you check out this project, run `npm install && npm run dev`, then there will be a live server with tests that you can run in your browser. :)

**Comment by Canifex** [comment] 2015-04-23 13:39
Thanks for the tip and this awesome support here! Everything works now flawlessly!

I am currently working on a peer2peer webrtc-based pouchdb replication, and combining these tools is nearly everything you need to get this running. Maybe this would be interesting for some more people (since https://github.com/natevw/PeerPouch is not up to date), currently I am wondering if I just open another repository for this use case or if we just maybe give a hint in the readme?

**Closed** 2015-04-23 14:09 UTC

**Comment by calvinmetcalf** [comment] 2015-04-23 14:15
ping @nateevw on this

**Comment by nolanlawson** [comment] 2015-04-23 14:56
I think building a PeerPouch 2.0 on top of pouchdb-replication-stream would be fabulous. :) If you could abstract your work into a plugin, that would be amazing.

Also please do update the README for this repo with the steps to get it running in the browser. Apparently MemoryStream doesn't work; would be good to know what does. :)
